= To-do list of Galope
:author: Marcos Cruz (programandala.net)
:revdate: 2017-08-24

== 2012-09-14

Rename 'seconds' and 'microseconds':

----
seconds/key
seconds|key
seconds-or-keypress
seconds|keypress
/seconds
----

Then use 'seconds' and 'microseconds' for versions where the pause
that can not be shortened with a keypress.

== 2012-09-20

r.s  [ 2015-02-03: better name: .rs ]

Idea:

----
: copy-name  ( "name" -- ca len )
  >in @ >r parse-name r> >in ! ;
----

== 2013-05-15

Idea found in
(<http://groups.google.com/group/comp.lang.forth/browse_thread/thread/7367894d3a9ac280/2829422a2a58b349>):

____
I use:
BEGIN-PRIVATE   \ remember dp #1
< definitions >
END-PRIVATE  \ remember dp #2
< definitions >
MAKE-PRIVATE  \ decapitate all definitions between dp #1 & #2
Clean and simple. Decapitate means, convert those defs to real nonames,
thereby freeing additional namespace.
Andreas
____

== 2013-05-28

Idea: reverse characters in a string,
done in <~/ext/comp/lang/forth/prg/util/misc/units/>.

== 2013-11-06

fix slash-sides.fs

== 2014-02-17

Create word sections, after Gforth, and mark them in the sources with
some conventional notation.  This way the files could be searched
(e.g. with 'grep') for words of specific sections.

== 2014-02-18

`2pick`, `picks`, `2picks`.

== 2014-02-23

Move the tool words of <galope/to-yyyymmddhhmmss.fs> to their own
files, when a similar word will need them.

== 2014-03-12

rename 'greater-of' to '>of' or 'greater-than-of'?
rename 'less-of' to '<of' or 'less-than-of'?
write '<>of'?

== 2014-03-13

'among-of' ( run-time: x0 x'1...x'n n )

----
x case
  a b c 3 among-of ... endof
  d e 2 among-of ... endof
  f g h i 4 among-of ... endof
endcase
----

== 2014-03-19


----
ANEW  --CHARSCAN--                            \  Wil Baden  2002-03-17

\  *******************************************************************
\  *                                                                 *
\  *  Wil Baden  2003-02-17                                          *
\  *                                                                 *
\  *      String Handling with Generalization of SKIP and SCAN       *

: Replace-Char                  ( str /str char char_2 -- )
    2SWAP BOUNDS ?DO
        over I C@ = IF  dup I C!  THEN
    LOOP 2DROP ;
----

Write 'replace-xchar' too.

== 2014-07-13

Use comment marks, to make automatic lists of the modules:

----
\ galope-tag: strings
\ galope-tag: time&date
\ galope-tag: control_structures
\ galope-tag: text_output
\ galope-tag: data_stack
\ galope-tag: return_stack
----

== 2015-11-27

Rename "x" files to "x-", after the spelling in Forth-2012.

== 2016-06-21, 2017-08-18

Replace underscore with hyphens in the `sb` module.

== 2016-07-13

Add Gforth-specific words which have an alternative definition in
standard Forth.

== 2017-07-16, 2017-08-17, 2017-08-20

Deprecate `--` and `++`; use `1-!` and `1+!` instead.

Deprecate `?--` and `?++`; use `?1-!` and `?1+!` instead.

Rename `decrement` to `?1-!`

== 2017-08-14

Improve and document `??` and `[??]`.

== 2017-08-14

Rename `?keep` and `?empty`.

== 2017-08-16

Add `module`, by Ulrich Hoffmann.

== 2017-08-16

Rename `\eof` to `\\`.

== 2017-08-17

Remove `[or]`.

== 2017-08-17

Rename <sarray.fs> to <s-array.fs>.

== 2017-08-17

Check dependency on `u+do` in `rolls`.

== 2017-08-17

Rewrite `#do` without `evaluate`.

== 2017-08-17

Finish or simplify or remove <headline.fs>.

== 2017-08-17

Homogenize "Author: Wil Baden" and "Taken from".

== 2017-08-18, 2017-08-20

Rename `break`: `debug`?

== 2017-08-19

Finish updating the change log layout:

----
gvim $(grep "Change\slog" *.fs -L)
----

== 2017-08-20

Rename `:create` to `created`.

Remove `?nip`?

Check if `$variable` is needed in Gforth 0.7.9.

Check if `$@len` is needed in Gforth 0.7.9.

Check if `$@` is needed in Gforth 0.7.9.

Fix: UTF-8 chars are corrupted in the PDF manual. See usage example of
`2arrayed`. The HTML version is fine.

